image: "ubuntu:latest"

before_script:
  - cd ~
  - apt-get update -qq
  - apt-get install --yes --force-yes openjdk-8-jdk
  - java -version
  - apt-get install --yes --force-yes curl
  - curl --version
  - apt-get install wget
  - apt-get install -y unzip
  - apt-get install --yes --force-yes git
  - git --version
  - cd ~
  - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip sdk-tools-linux-3859397.zip -d android-sdk
  - export ANDROID_HOME="$PATH:`pwd`/android-sdk"
  - export PATH="$PATH:`pwd`/android-sdk/platform-tools"
  - export PATH="$PATH:`pwd`/android-sdk/tools/bin"
  - sdkmanager --list
  - sdkmanager "platform-tools" "platforms;android-28"
  - adb devices
#  - wget https://services.gradle.org/distributions/gradle-5.6.2-all.zip
#  - unzip gradle-5.6.2-all.zip -d gradle
  - git clone https://github.com/flutter/flutter.git -b v1.12.13+hotfix.5
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v

test:
  script:
    - echo done