image: "ubuntu:latest"

before_script:
  - cd ~
  - apt-get update -qq
  - apt-get install --yes --force-yes openjdk-8-jdk
  - java -version
  - apt-get install --yes --force-yes curl
  - curl --version
  - apt-get install wget
  - apt-get install -y unzip
  - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip sdk-tools-linux-3859397.zip -d android-sdk
  - cd android-sdk/tools
  - ./bin/sdkmanager --list
  - ./bin/sdkmanager --update
  - export ANDROID_HOME=/opt/android-sdk
  - export PATH=$PATH:/opt/android-sdk/platform-tools
  - export PATH=$PATH:/opt/android-sdk/tools
  - cd ~
  - apt-get install -y libc6:i386 libstdc++6:i386 zlib1g:i386
  - wget https://services.gradle.org/distributions/gradle-5.6.2-all.zip
  - unzip gradle-5.6.2-all.zip -d gradle

test:
  script:
    - echo done