image: "ubuntu:latest"

before_script:
  - apt-get update -qq
  - apt-get install --yes --force-yes openjdk-8-jdk
  - java -version
  - apt-get install --yes --force-yes curl
  - curl --version
  - apt-get install wget
  - apt-get install -y unzip
  - wget https://dl.google.com/android/repository/sdk-tools-linux-6609375.zip
  - unzip sdk-tools-linux-6609375.zip -d android-sdk
  - ls
#  - export PATH=/opt/pradip/tools:/opt/pradip/tools/bin:$PATH

test:
  script:
    - echo done