image: "ubuntu:latest"

before_script:
  - apt-get update -qq
  - apt-get install --yes --force-yes openjdk-8-jdk
  - java -version
  - curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | sudo bash
  - apt-get install gitlab-runner

test:
  script:
    - java -version