image: "ubuntu:latest"

before_script:
  - cd ~
  - apt-get update -qq
  - apt-get install --yes --force-yes openjdk-8-jdk
  - java -version
  - apt-get install --yes --force-yes curl
  - curl --version
  - apt-get install wget
  - apt-get install -y unzip
  - apt-get install --yes --force-yes git
  - git --version
  - cd ~
  - wget https://dl.google.com/android/repository/sdk-tools-linux-3859397.zip
  - unzip sdk-tools-linux-3859397.zip -d android-sdk
  - export ANDROID_HOME="$PATH:`pwd`/android-sdk"
  - export PATH="$PATH:`pwd`/android-sdk/platform-tools"
  - export PATH="$PATH:`pwd`/android-sdk/tools/bin"
  - echo y | sdkmanager "platforms;android-29"
  - echo y | sdkmanager "platform-tools"
  - echo y | sdkmanager "build-tools;29.0.3"
  - echo y | sdkmanager "extras;android;m2repository"
  - echo y | sdkmanager "extras;google;m2repository"
  - echo y | sdkmanager "system-images;android-29;google_apis_playstore;x86_64"
  - echo no | avdmanager create avd -n android29 -k "system-images;android-29;google_apis_playstore;x86_64"
  - emulator -avd android29 -netdelay none -netspeed full
  - git clone https://github.com/flutter/flutter.git -b v1.12.13+hotfix.5
  - export PATH="$PATH:`pwd`/flutter/bin"
  - flutter doctor -v
  - echo y | flutter doctor --android-licenses
  - flutter packages get
  - flutter clean

test:
  script:
    - flutter test test/home_page_bloc_test.dart
    - test test/home_page_test.dart